// Solution by Vladislav Pavlov
// Difficulty: Easy
// Topics: Hash Table, String, Bit Manipulation, Sorting
//
//You are given two strings s and t.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Return the letter that was added to t.
//
// 
//
//Example 1:
//
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.
//Example 2:
//
//Input: s = "", t = "y"
//Output: "y"


class Solution {
    func findTheDifference(_ s: String, _ t: String) -> Character {
        guard !s.isEmpty else { return Character(t) }
        
        var sCounter: [Int] = Array(repeating: 0, count: 26)
        var tCounter: [Int] = Array(repeating: 0, count: 26)
        
        for i in s.unicodeScalars {
            sCounter[Int(i.value) - 97] += 1
        }
        for j in t.unicodeScalars {
            tCounter[Int(j.value) - 97] += 1
        }
        
        var result = Character(" ")
        
        for k in 0..<26 where tCounter[k] != sCounter[k] {
            result = Character(Unicode.Scalar(97 + k) ?? " ")
            return result
        }
        
        return result
    }
}
